# Generated by Django 3.2 on 2024-06-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
