# Generated by Django 3.2 on 2024-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registertable_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registertable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
